Add put_to_self_logical example
BullSequana/portails4 pull request #18
Opened 2024-07-19 13:37 UTC by CamilleEviden

2024-07-19 15:04 UTC, pichong commented on examples/put_to_self_logical.c
> +	ret = PtlEQWait( eqh, & ev);
should rather use a loop to retrieve the three events since there they can arrive in any order (like in put_to_self.c)

2024-07-22 14:35 UTC, boyerq requested changes

2024-07-22 14:35 UTC, boyerq commented on examples/README.md
> +* **put_to_self_logical** : show the sending of a message and it's ack using a logical interface.
show -> demonstrate
it's -> its

I think we should put this example just after the `put_to_self` in the list

2024-07-22 14:35 UTC, boyerq commented on examples/put_to_self_logical.c
> +			NULL, & nih);
`clang-format`

2024-07-23 12:33 UTC, pichong approved these changes

2024-07-23 13:40 UTC, boyerq approved these changes

2024-07-23 13:41 UTC, merged